writerError            = rolling file
writerError.tag        = error 
writerError.file       = error_{count}.log 
writerError.buffered   = true 
writerError.policies   = startup, daily

writerAccess           = rolling file 
writerAccess.tag       = access 
writerAccess.file      = access_{count}.log 
writerAccess.level     = info
writerAccess.buffered  = true 
writerAccess.policies  = startup, daily

writerConsole          = console
writerConsole.tag      = error 
writerConsole.level    = info 
writerConsole.format   = {level}: {message}
