# Sample keplerd configuration file

debug.enable_test_page=true

# Access control settings
security.enabled=true
security.roles_file=etc/roles.properties

# Logging settings
logging.error.file=/tmp/error_{count}.log
# Error log level can be off, error, warn, info, debug, or trace.
logging.error.level=info
logging.access.file=/tmp/access_{count}.log

# Server configuration
server0.type=kepler
server0.docroot=sample_docroot/

server1.type=keplers
server1.docroot=sample_docroot/
server1.keystore_file=etc/server_keystore.jks
server1.keystore_password=changeit

server2.type=gemini
server2.docroot=sample_docroot/
server2.keystore_file=etc/server_keystore.jks
server2.keystore_password=changeit

server3.type=spartan
server3.docroot=sample_docroot/

# Extension configuration

extension0.jar=file:binaries/cal-0.2.jar
extension0.context_root=/cal

extension1.jar=file:binaries/weather-0.2.jar
extension1.context_root=/weather

