debug.enable_test_page=true
security.enabled=true
security.roles_file=samples/roles.properties

server0.type=kepler
server0.docroot=/home/kevin/docs/gmi2/_site_gemini/

server1.type=keplers
server1.docroot=/home/kevin/docs/gmi2/_site_gemini/
server1.keystore_file=samples/server_keystore.jks
server1.keystore_password=changeit

server2.type=gemini
server2.docroot=/home/kevin/docs/gmi2/_site_gemini/
server2.keystore_file=samples/server_keystore.jks
server2.keystore_password=changeit

server3.type=spartan
server3.docroot=/home/kevin/docs/gmi2/_site_gemini/



