# Sample keplerd configuration file

debug.enable_test_page=true

# Access control settings
security.enabled=true
security.roles_file=samples/roles.properties

# Logging settings
logging.error.file=/tmp/error_{count}.log
# Error log level can be off, error, warn, info, debug, or trace.
logging.error.level=info
logging.access.file=/tmp/access_{count}.log

# Server configuration
server0.type=kepler
server0.docroot=/home/kevin/docs/gmi2/_site_gemini/

server1.type=keplers
server1.docroot=/home/kevin/docs/gmi2/_site_gemini/
server1.keystore_file=samples/server_keystore.jks
server1.keystore_password=changeit

server2.type=gemini
server2.docroot=/home/kevin/docs/gmi2/_site_gemini/
server2.keystore_file=samples/server_keystore.jks
server2.keystore_password=changeit

server3.type=spartan
server3.docroot=/home/kevin/docs/gmi2/_site_gemini/

